# Configuração específica para Coolify
version: '1'

services:
  backend:
    type: application
    dockerfile: backend/Dockerfile
    environment:
      - MINIO_ENDPOINT
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_SECURE
      - MINIO_BUCKET
      - CORS_ORIGINS
      - WORDPRESS_API_URL
      - WORDPRESS_USERNAME
      - WORDPRESS_PASSWORD
    healthcheck:
      enabled: true
      url: '/health'
      method: 'GET'
      interval: 30
      timeout: 10
      retries: 3
    ports:
      - 8000
    resource:
      cpu: 0.5
      memory: 512

  frontend:
    type: application
    dockerfile: frontend/Dockerfile.prod
    environment:
      - REACT_APP_API_URL
    healthcheck:
      enabled: true
      url: '/health'
      method: 'GET'
      interval: 30
      timeout: 10
      retries: 3
    ports:
      - 80
    resource:
      cpu: 0.5
      memory: 256

deployment:
  compose_file: docker-compose.prod.yml
  restart_policy: unless-stopped
  
network:
  attachable: true

volumes:
  - name: app_data
    path: /app/data 