version: '3.8'

services:
  # Backend FastAPI
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      # MinIO Configuration
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE:-false}
      - MINIO_BUCKET=${MINIO_BUCKET:-tecnomyl}
      
      # WordPress Integration (opcional)
      - WORDPRESS_API_URL=${WORDPRESS_API_URL:-}
      - WORDPRESS_USERNAME=${WORDPRESS_USERNAME:-}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD:-}
      
      # CORS Configuration
      - CORS_ORIGINS=${CORS_ORIGINS}
      
      # Authentication Configuration (Single User)
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_EXPIRE_HOURS=${JWT_EXPIRE_HOURS:-24}
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || python3 healthcheck.py || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s

  # Frontend React
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_APP_NAME=Upload Tecnomyl
        - REACT_APP_ENV=production
    expose:
      - "80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: unless-stopped 