version: '3.8'

services:
  # MinIO para desenvolvimento local (se necessário)
  minio:
    image: minio/minio:latest
    container_name: tecnomyl-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - tecnomyl-network

  # Backend Python
  backend:
    build: ./backend
    container_name: tecnomyl-backend
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SECURE=False
      - MINIO_BUCKET=tecnomyl
    depends_on:
      - minio
    volumes:
      - ./backend:/app
    networks:
      - tecnomyl-network

  # Frontend React
  frontend:
    build: ./frontend
    container_name: tecnomyl-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tecnomyl-network

volumes:
  minio_data:

networks:
  tecnomyl-network:
    driver: bridge 