version: '3.8'

services:
  # Backend Python
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: tecnomyl-backend
    expose:
      - "8000"
    environment:
      # MinIO Configuration (usar variáveis de ambiente do Coolify)
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio.exemplo.com:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE:-true}
      - MINIO_BUCKET=${MINIO_BUCKET:-tecnomyl}
      
      # WordPress Integration (opcional)
      - WORDPRESS_API_URL=${WORDPRESS_API_URL:-}
      - WORDPRESS_USERNAME=${WORDPRESS_USERNAME:-}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD:-}
      
      # CORS Configuration
      - CORS_ORIGINS=${CORS_ORIGINS:-https://tecnomyl-upload.exemplo.com}
      
      # Authentication Configuration (Single User)
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_EXPIRE_HOURS=${JWT_EXPIRE_HOURS:-24}
      
    restart: unless-stopped
    networks:
      - tecnomyl-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React (Build Production)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: tecnomyl-frontend
    expose:
      - "80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-https://api.tecnomyl-upload.exemplo.com}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tecnomyl-network

networks:
  tecnomyl-network:
    driver: bridge 